channels:
  - defaults
dependencies:
   - python=3.8
   - scipy
   - pip
   - pip:
      - pystoi
      - https://github.com/schmiph2/pysepm/archive/master.zip
      - speechmetrics

# pysepm
# install_requires=[
#        'numpy',
#       'scipy',
#         'numba',
#       'pystoi',
#       'pesq @ https://github.com/ludlows/python-pesq/archive/master.zip#egg=pesq',
#       'SRMRpy @  https://github.com/jfsantos/SRMRpy/archive/master.zip#egg=SRMRpy',
#    ],

# pystoi
#     install_requires=['numpy', 'scipy'],




# speechmetrics
#     install_requires=[
#         'numpy',
#         'scipy',
#         'tqdm',
#         'resampy',
#         'pystoi',
#         'museval',
#         # This is requred, but srmrpy pull it in,
#        # and there is a pip3 conflict if we have the following
#        # line.
#         #'gammatone @ git+https://github.com/detly/gammatone',
#         'pypesq @ git+https://github.com/vBaiCai/python-pesq',
#         'srmrpy @ git+https://github.com/jfsantos/SRMRpy',
#         'pesq @ git+https://github.com/ludlows/python-pesq',
#     ],

